application: joel-galleria
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images/
- url: /js
  static_dir: static/js/
- url: /css
  static_dir: static/css/
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /admin.*
  script: main.py
- url: /.*
  script: main.py